---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    # --- MC ---
    - name: Install midnight commander
      package:
        name: mc
        state: present
     # --- Steam ---
    - name: Install Steam
      apt:
        name: steam
        state: present
    # --- Snap + Spotify ---
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Ensure snapd is running
      systemd:
        name: snapd
        enabled: yes
        state: started

    - name: Install Spotify via snap
      community.general.snap:
        name: spotify
        state: present

    
