---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    # --- MC ---
    - name: Install midnight commander
      package:
        name: mc
        state: present
     # --- Steam ---
    - name: Enable i386 architecture
      command: dpkg --add-architecture i386

    - name: Ensure main Ubuntu repos (including multiverse) are enabled
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe multiverse restricted"
        state: present

    - name: Ensure updates repo is enabled (important for i386 libs)
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main universe multiverse restricted"
        state: present

    - name: Update apt cache AFTER adding repos and i386
      apt:
        update_cache: yes
    
    - name: Install Steam
      apt:
        name: steam-installer
        state: present
    # --- Snap + Spotify ---
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Ensure snapd is running
      systemd:
        name: snapd
        enabled: yes
        state: started

    - name: Install Spotify via snap
      community.general.snap:
        name: spotify
        state: present

    
